### ISSUE TITLE
Support for passing parameter

### ISSUE THREAD

**Issue by cemo** [stormcat24/ecs-formation#37]
I would like to pass tag of my docker image as a parameter as this:

```
  image: xxx/yyy:${docker_image_paramater}
``` 

Is it possible to support this?

Thanks for your project.

**Comment by stormcat24** [comment]
Sounds good. :+1: 

I'm going to support this plan by command line options, what do you think?

**Comment by cemo** [comment]
Would be super cool.

**Comment by stormcat24** [comment]
@cemo Sorry for delay. I resolved this issue. Please check it out.

https://github.com/stormcat24/ecs-formation#passing-custom-parameters

**Comment by cemo** [comment]
Thanks for your time @stormcat24. I will give a try this week.
